# Form implementation generated from reading ui file 'CargarImagen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DOS(object):
    def setupUi(self, DOS):
        DOS.setObjectName("DOS")
        DOS.resize(597, 483)
        self.CargarImagen = QtWidgets.QPushButton(parent=DOS)
        self.CargarImagen.setGeometry(QtCore.QRect(70, 170, 101, 24))
        self.CargarImagen.setObjectName("CargarImagen")
        self.Camara = QtWidgets.QPushButton(parent=DOS)
        self.Camara.setGeometry(QtCore.QRect(70, 140, 101, 24))
        self.Camara.setObjectName("Cam")
        
        self.Previsualizacion = QtWidgets.QGraphicsView(parent=DOS)
        self.Previsualizacion.setGeometry(QtCore.QRect(310, 70, 211, 321))
        self.Previsualizacion.setObjectName("Previsualizacion")
        self.IraEditarCargada = QtWidgets.QPushButton(parent=DOS)
        self.IraEditarCargada.setGeometry(QtCore.QRect(30, 220, 75, 24))
        self.IraEditarCargada.setObjectName("IraEditarCargada")
        self.VolverVentanaPrincipal = QtWidgets.QPushButton(parent=DOS)
        self.VolverVentanaPrincipal.setGeometry(QtCore.QRect(130, 220, 75, 24))
        self.VolverVentanaPrincipal.setObjectName("VolverVentanaPrincipal")
   

        self.retranslateUi(DOS)
        QtCore.QMetaObject.connectSlotsByName(DOS)

    def retranslateUi(self, DOS):
        _translate = QtCore.QCoreApplication.translate
        DOS.setWindowTitle(_translate("DOS", "Form"))
        self.CargarImagen.setText(_translate("DOS", "Cargar Imagen"))
       
        self.IraEditarCargada.setText(_translate("DOS", "Aceptar"))
        self.VolverVentanaPrincipal.setText(_translate("DOS", "Volver"))
        self.Camara.setText(_translate("DOS", "Camara"))

       

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DOS = QtWidgets.QWidget()
    ui = Ui_DOS()
    ui.setupUi(DOS)
    DOS.show()
    sys.exit(app.exec())
