# Form implementation generated from reading ui file 'Principal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_uno(object):
    def setupUi(self, uno):
        uno.setObjectName("uno")
        uno.resize(599, 364)
        self.centralwidget = QtWidgets.QWidget(parent=uno)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo1 = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.Logo1.setGeometry(QtCore.QRect(90, 30, 421, 161))
        self.Logo1.setObjectName("Logo1")
        self.EditarFoto = QtWidgets.QPushButton(parent=self.centralwidget)
        self.EditarFoto.setGeometry(QtCore.QRect(170, 270, 75, 24))
        self.EditarFoto.setObjectName("EditarFoto")
        self.AbrirCamara = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AbrirCamara.setGeometry(QtCore.QRect(350, 270, 75, 24))
        self.AbrirCamara.setObjectName("AbrirCamara")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 230, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 240, 81, 16))
        self.label_2.setObjectName("label_2")
        uno.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=uno)
        self.statusbar.setObjectName("statusbar")
        uno.setStatusBar(self.statusbar)

        self.retranslateUi(uno)
        QtCore.QMetaObject.connectSlotsByName(uno)
        uno.setTabOrder(self.Logo1, self.EditarFoto)
        uno.setTabOrder(self.EditarFoto, self.AbrirCamara)

    def retranslateUi(self, uno):
        _translate = QtCore.QCoreApplication.translate
        uno.setWindowTitle(_translate("uno", "MainWindow"))
        self.EditarFoto.setText(_translate("uno", "Editar"))
        self.AbrirCamara.setText(_translate("uno", "Abrir"))
        self.label.setText(_translate("uno", "Editar Imagen"))
        self.label_2.setText(_translate("uno", "Abrir Camara"))

        pixmap = QtGui.QPixmap("./Imagenes/log1.png")
        scene = QtWidgets.QGraphicsScene()
        pixmap_item = QtWidgets.QGraphicsPixmapItem(pixmap)
        scene.addItem(pixmap_item)
        self.Logo1.setScene(scene)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    uno = QtWidgets.QMainWindow()
    ui = Ui_uno()
    ui.setupUi(uno)
    uno.show()
    sys.exit(app.exec())
